from trainers.esrgan_trainer import ESRGANLoggerTrainer, ESRGANTrainer
from trainers.srgan_trainer import SRGANLoggerTrainer, SRGANTrainer
from trainers.srresnet_trainer import SRResNetLoggerTrainer, SRResNetTrainer
from trainers.srrrdbnet_trainer import SRRRDBNetLoggerTrainer, SRRRDBNetTrainer
